### ISSUE TITLE
Remove High Priority Bug  - wged

### ISSUE THREAD

**Issue by mjblowers** [BoiseState/CS471-S19-ProjectWarmup#34] opened 2019-02-26 00:13 UTC
#1
PlatformManager.java
@BUG HighPriority - wged (2 of 3) ->|
@BUG HighPriority - wged (2 of 3) ->|package com.mucommander;
@BUG HighPriority - wged (2 of 3) ->|

**Comment by mjblowers** [comment] 2019-02-26 00:15
References issue #1

**Comment by joshchamberlain** [comment] 2019-02-26 00:41
This is a duplicate of #8. Closing bug.

**Closed by joshchamberlain** 2019-02-26 00:41 UTC
