### ISSUE TITLE
Remove Medium Priority Bug - lexo

### ISSUE THREAD

**Issue by The-Kanine** [BoiseState/CS471-S19-ProjectWarmup#44] opened 2019-02-26 00:17 UTC
References #2.

Fix the bug 'lexo' in:

 src/main/java/com/mucommander/core/LocalLocationHistory.java Line 19
 src/main/java/com/mucommander/muCommander.java Line 51

**Comment by joshchamberlain** [comment] 2019-02-26 00:37
This is a duplicate of #9. Closing this bug.

**Closed by joshchamberlain** 2019-02-26 00:37 UTC
Labels: bug, priority-medium
